version: "3"

services:
  server:
    container_name: BACKEND_TRIPYOU
    build: .
    restart: always
    command: ["yarn", "dev:server"]
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    links:
      - mongo

  mongo:
    container_name: DATABASE_TRIPYOU
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
